# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
            node-version: 16.x
            cache: 'npm'
      - run: npm install
      - run: npm build
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build'
          destination-github-username: 'storkeus'
          destination-repository-name: 'pneumonia-backend'
          user-email: bartosz.lyzwa@o2.pl
          commit-message: Updated application build $GITHUB_REF
          target-branch: main
